FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /workspace/app
COPY pom.xml .

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/app/target/*.jar app.jar

RUN addgroup --system spring && adduser --system spring --ingroup spring

USER spring:spring
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]